config/routes.rb
Rails.application.routes.draw do
  get 'export/prog', to:'export#prog'
  get 'export/index'
  get 'export', to: 'export#index'
  post 'export/create', to: 'export#create'
  get 'anisyncs/index'
  get 'anisync', to: 'anisyncs#index'
  get 'anisyncs/remove'
  delete 'anisyncs', to: 'anisyncs#destroy'
  resources :anisyncs, only: [:index, :new, :create]
  get 'home/index'

  root 'home#index'

end

app/models/anime.rb
class Anime < ActiveRecord::Base
end

app/models/anisync.rb
class Anisync < ActiveRecord::Base
end

app/models/manga.rb
class Manga < ActiveRecord::Base
end

app/controllers/anisyncs_controller.rb
class AnisyncsController < ApplicationController
  def index
    @anisync = Anisync.new
    @anisyncs = Anisync.all
  end

  def create
    parameters = {:grant_type => "authorization_pin", :client_id => "cor-loasb",
      :client_secret => ENV["CLIENT_SECRET"], :code => params[:anisync][:token]}
    a = HTTP.post("http://anilist.co/api/auth/access_token", :params => parameters)
    auth = JSON.parse(a.to_s)
    params[:anisync][:refresh] = auth["refresh_token"]
    params[:anisync][:token] = auth["access_token"]
    @anisync = Anisync.new(anisync_params)
    @anisync.save

    redirect_to "/anisyncs"
  end

  def remove
    @anisync = Anisync.new
  end

  def destroy
    puts params
    @anisync = Anisync.where(username: params[:anisync][:username]).where(password: params[:anisync][:password]).each do |u|
      u.destroy
    end

    redirect_to "/anisyncs"
  end

  private
    def anisync_params
      params.require(:anisync).permit(:username, :password, :token, :refresh, :alusername)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
  $progress = {}

  def index
    @anisync = Anisync.new
  end

  def create
    @user = params[:anisync][:alusername]
    respond_to do | format |
      format.html { redirect_to export_url }
      format.js
    end

    process = Thread.new(@user) do |user|
      parameters = {:grant_type => "authorization_pin", :client_id => "cor-loasb",
        :client_secret => ENV["CLIENT_SECRET"], :code => params[:anisync][:token]}
      a = HTTP.post("http://anilist.co/api/auth/access_token", :params => parameters)
      @auth = JSON.parse(a.to_s)
      if @auth['access_token'] != nil
        $progress[user] = "<p>Account succesfully authenticated. Exporting, this may take a while.</p><p>Downloading your list...</p>"
      else
        $progress[user] = "<p>Error! Could not authenticate. Refresh and try again.</p>"
        return
      end

      output = '''<?xml version="1.0" encoding="UTF-8" ?>
  <!--
  Created by AniSync
  Programmed by Cor
  -->

<myanimelist>
  <myinfo>
    <user_id>5459046</user_id>
    <user_name>testcor</user_name>
    <user_export_type>1</user_export_type>
    <user_total_anime>0</user_total_anime>
    <user_total_watching>0</user_total_watching>
    <user_total_completed>0</user_total_completed>
    <user_total_onhold>0</user_total_onhold>
    <user_total_dropped>0</user_total_dropped>
    <user_total_plantowatch>0</user_total_plantowatch>
  </myinfo>
'''

      list = HTTP.auth("Bearer " + @auth['access_token']).get("http://anilist.co/api/user/" + user + "/animelist").to_s

      #should probably move this somewhere else
      def get_mal(anime)
        return anime['id'].to_s if anime['id'].to_i < 19285
        existing = Anime.where(:alid => anime['id']).all
        return existing[0][:malid].to_s if existing.size > 0
        show = {'q' => anime['title_romaji']}
        r = HTTP.get("http://myanimelist.net/anime.php", :params => show)
        c = r.to_s
	n = 1
	ani_id = 0
	while ani_id.to_i < 19285
        	ani_id = (c.split('<a class="hoverinfo_trigger')[n].split('http://myanimelist.net/anime/')[1].split("/")[0])
		n += 1
	end
        puts "Adding this with mal id: " + ani_id
        b = Anime.new({:alid => anime['id'], :malid => ani_id})
        b.save
        return ani_id
      end

      #$progress[@user] += list
      count = 0
      puts "doin a thing"
      all = JSON.parse(list)
      all['lists'].merge(all['custom_lists']).each do |t, sublist|
        sublist.each do |anime|
	type = anime['list_status']
	  next if type == ""
	  count += 1
          output += "\t<anime>\n"
          #$progress[user] += '<p>' + anime['list_status'] + " " + anime['anime']['id'].to_s + " " + anime['episodes_watched'].to_s + '</p>'
          score = anime['score_raw']
	  score += 5 if score < 5 && score > 0
	  score = (score + 5) / 10
          output += "\t\t<update_on_import>1</update_on_import>\n"
          output += "\t\t<series_animedb_id>" + get_mal(anime['anime']).to_s + "</series_animedb_id>\n"
          output += "\t\t<my_watched_episodes>" + anime['episodes_watched'].to_s + "</my_watched_episodes>\n"
          output += "\t\t<my_status>" + {"watching" => "Watching", "completed" => "Completed", "plan to watch" => "Plan to Watch", "on-hold" => "On-Hold", "dropped" => "Dropped"}[type] + "</my_status>\n"
          output += "\t\t<my_score>" + score.to_s + "</my_score>\n"
          #$progress[user] += get_mal(anime['anime'])
          $progress[user] = "<p>Account succesfully authenticated. Exporting, this may take a while.</p><p>Titles finished: #{count}</p>"
          output += "\t</anime>\n"
        end
      end

      output += '</myanimelist>'
      puts "done"
      File.write('app/assets/images/' + user + '.xml', output)
      $progress[user] = "<a href=http://cory.pw/assets/" + user + ".xml>http://cory.pw/assets/" + user + '.xml</a>
      <p>To save this file, right click and hit "Save link as..."</p>'
    end
  end

  def prog
    puts params
    respond_to do |format|
      format.text { render :text => $progress[params[:name]]}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/anisyncs_helper.rb
module AnisyncsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/anisyncs/index.html.erb
<h1>AniSync</h1>

<p>To export your AniList to MAL .xml format, click <%= link_to 'here', export_url %></p>
<p>First, connect your Anilist account and paste the authorization pin into the form below</p>
<iframe scrolling="no" src="http://anilist.co/api/auth/authorize?grant_type=authorization_pin&client_id=cor-loasb&response_type=pin"></iframe>
<%= form_for @anisync do |u| %>
<p>
  <%= u.label "Authorization Pin" %>
  <%= u.text_field :token %>
</p>
<p>
  Anilist username
  <%= u.text_field :alusername %>
</p>

<br>
<p>Now, enter your MyAnimeList credentials<p>
<p>
  <%= u.label :username %>
  <%= u.text_field :username %>
</p>
<p>
  <%= u.label :password %>
  <%= u.password_field :password %>
</p>

<%= u.submit "Submit" %>
<% end %>

<p> To unlink your account, click <%= link_to 'here', anisyncs_remove_url %></p>

<p>Registered users:<p>
<% @anisyncs.each do |anisync| %>
  <p><%= anisync.alusername %> / <%= anisync.username %>
<% end %>

app/views/anisyncs/remove.html.erb
<h1>Unlink your account</h1>
<p>If you unlink your account, Anisync will stop updating your MAL.<br>However, you are free to re-register to make Anisync active again</p>

<%= form_for @anisync, method: :delete do |u| %>
  <p>
    MAL Username
    <%= u.text_field :username %>
  </p>
  <p>
    <%= u.label :password %>
    <%= u.password_field :password %>
  </p>

  <%= u.submit "Submit" %>
<% end %>

app/views/export/create.html.erb
<h2>Exporting your AniList to MAL Format...</h1>
<p>This may take a while. Since MAL uses a different format and has different ID's for anime,
  the system needs to search for the corresponding shows on MyAnimeList.<br>As a result, a few shows
  may not export correctly, so please know that this export feature may not be 100% reliable.</p>

app/views/export/create.js.erb
$("#prog").html("Please wait...");
$("#login").css("display", "none");

var update = function() {
  $.ajax("/export/prog?name=<%= @user %>").done(function(data) {
    $('#prog').html(data);
  });
}

setInterval(update, 1500);

app/views/export/export.html.erb
meme

app/views/export/index.html.erb
<h1>Export to .xml</h1>

<div id="login"</div>
  <iframe scrolling="no" src="http://anilist.co/api/auth/authorize?grant_type=authorization_pin&client_id=cor-loasb&response_type=pin"></iframe>
  <%= form_for @anisync, url: export_create_url, remote: true do |u| %>
  <p>
    <%= u.label "Authorization Pin" %>
    <%= u.text_field :token %>
  </p>
  <p>
    Anilist username
    <%= u.text_field :alusername %>
  </p>
  <%= u.submit "Submit" %>
  <% end %>
</div>

<div id="prog">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AniSync</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>